### ISSUE TITLE
Libnice Thread taking 100% CPU in case of TCP Low Bandwidth 

### ISSUE THREAD

**Issue by puneet89** [Kurento/libnice#4]
Hi @ocrete 

I am running a use case where there are 2 Users sending audio/video over TCP every thing works fine when Bandwidth is good , as soon as bandwidth goes down and tcp transmission happen libnice CPU goes to 100 % . I have taken gdb backtrace ,can you please analyse and help us to resolve same .
I have one router configured with low bandwidth and i am able to reproduce this issue 100% times , TCP over low bandwidth . 
we are stuck with this issue as this issue frequently coming in corporate network where UDP is blocked and TCP having low bandwidth . 
I am not 100% sure but it seems that issue coming only in case of low bandwidth where re transmission happens. Let me now if you need more logs . 

it  mostly stuck on :
 0x00007fd773dd4a31 <+161>:   jne    0x7fd773dd4a39 <g_socket_get_available_bytes+169>ioctl

STRACE : 
write(161<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8
poll([{fd=161<anon_inode:[eventfd]>, events=POLLIN}, {fd=162<UDP:[20.3.20.240:12637]>, events=POLLIN}, {fd=163<TCP:[20.3.20.240:9878]>, events=POLLIN}, {fd=247<TCP:[20.3.20.240:9878->122.180.214.76:51782]>, events=POLLIN}, {fd=248<TCP:[20.3.20.240:9878->122.180.214.76:51784]>, events=POLLIN}, {fd=249<TCP:[20.3.20.240:9878->122.180.214.76:51786]>, events=POLLIN}, {fd=250<TCP:[20.3.20.240:9878->122.180.214.76:51783]>, events=POLLIN}, {fd=251<TCP:[20.3.20.240:9878->122.180.214.76:51785]>, events=POLLIN}, {fd=253<TCP:[20.3.20.240:9878->122.180.214.76:51789]>, events=POLLIN}], 9, -1) = 6 ([{fd=161, revents=POLLIN}, {fd=247, revents=POLLIN}, {fd=248, revents=POLLIN}, {fd=249, revents=POLLIN}, {fd=250, revents=POLLIN}, {fd=251, revents=POLLIN}])
read(161<anon_inode:[eventfd]>, "\n\0\0\0\0\0\0\0", 16) = 8
write(161<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8
ioctl(247<TCP:[20.3.20.240:9878->122.180.214.76:51782]>, FIONREAD, [4525]) = 0
write(161<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8
write(161<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8
ioctl(248<TCP:[20.3.20.240:9878->122.180.214.76:51784]>, FIONREAD, [2737]) = 0
write(161<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8
write(161<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8
ioctl(249<TCP:[20.3.20.240:9878->122.180.214.76:51786]>, FIONREAD, [5846]) = 0
write(161<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8
write(161<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8
ioctl(250<TCP:[20.3.20.240:9878->122.180.214.76:51783]>, FIONREAD, [3352]) = 0
write(161<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8
write(161<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8
ioctl(251<TCP:[20.3.20.240:9878->122.180.214.76:51785]>, FIONREAD, [2860]) = 0
write(161<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8

GDB trace :
(gdb) bt
#0  0x00007fd777ec44bd in write () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fd776e01832 in g_wakeup_signal (wakeup=0x5653be88a1c0) at /build/glib2.0-7ZsPUq/glib2.0-2.48.2/./glib/gwakeup.c:239
#2  0x00007fd776dba7e6 in g_main_context_add_poll_unlocked (context=<optimized out>, priority=<optimized out>, fd=<optimized out>) at /build/glib2.0-7ZsPUq/glib2.0-2.48.2/./glib/gmain.c:4262
#3  0x00007fd776dba890 in unblock_source (source=source@entry=0x7fd72c040d40)
    at /build/glib2.0-7ZsPUq/glib2.0-2.48.2/./glib/gmain.c:3085
#4  0x00007fd776dbe1d0 in g_main_context_dispatch (context=0x7fd720153100)
    at /build/glib2.0-7ZsPUq/glib2.0-2.48.2/./glib/gmain.c:3169
#5  0x00007fd776dbe1d0 in g_main_context_dispatch (context=context@entry=0x7fd720153100)
    at /build/glib2.0-7ZsPUq/glib2.0-2.48.2/./glib/gmain.c:3769
#6  0x00007fd776dbe3f0 in g_main_context_iterate (context=0x7fd720153100, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /build/glib2.0-7ZsPUq/glib2.0-2.48.2/./glib/gmain.c:3840
#7  0x00007fd776dbe712 in g_main_loop_run (loop=0x7fd720152f70) at /build/glib2.0-7ZsPUq/glib2.0-2.48.2/./glib/gmain.c:4034
#8  0x00007fd756cc7f14 in  () at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstnice15.so
#9  0x00007fd7736c3f46 in gst_base_src_get_range (src=src@entry=0x7fd75c05dbd0 [GstNiceSrc], offset=offset@entry=18446744073709551615, length=4096, buf=buf@entry=0x7fd718ff0c78) at gstbasesrc.c:2460
#10 0x00007fd7736c5b25 in gst_base_src_loop (pad=0x7fd75c054710 [GstPad]) at gstbasesrc.c:2736
#11 0x00007fd777378c5b in gst_task_func (task=0x7fd72c04f5f0 [GstTask]) at gsttask.c:344
#12 0x00007fd776de55ee in g_thread_pool_thread_proxy (data=<optimized out>)
    at /build/glib2.0-7ZsPUq/glib2.0-2.48.2/./glib/gthreadpool.c:307
#13 0x00007fd776de4c55 in g_thread_proxy (data=0x7fd73408e370) at /build/glib2.0-7ZsPUq/glib2.0-2.48.2/./glib/gthread.c:780
#14 0x00007fd777ebb6ba in start_thread (arg=0x7fd718ff1700) at pthread_create.c:333
#15 0x00007fd77587b41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) c
Continuing.
^Cn
Program received signal SIGINT, Interrupt.
0x00007fd775870f47 in ioctl () at ../sysdeps/unix/syscall-template.S:84
84      ../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) bt
#0  0x00007fd775870f47 in ioctl () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fd773dd4a10 in g_socket_get_available_bytes (socket=0x7fd72c015e50 [GSocket])
    at /build/glib2.0-7ZsPUq/glib2.0-2.48.2/./gio/gsocket.c:2705
#2  0x00007fd77083f26d in agent_recv_message_unlocked (agent=agent@entry=0x7fd72406f3f0 [NiceAgent], stream=stream@entry=0x7fd720149840 [NiceStream], component=component@entry=0x7fd720149ca0 [NiceComponent], nicesock=0x7fd750010190, message=message@entry=0x7fd718fe08d0) at agent.c:3780
#3  0x00007fd77084040e in component_io_cb (gsocket=<optimized out>, condition=<optimized out>, user_data=0x7fd75c03da20)
    at agent.c:5298
#4  0x00007fd773dd3901 in socket_source_dispatch (source=0x7fd72c040d40, callback=0x7fd77083fe20 <component_io_cb>, user_data=0x7fd75c03da20) at /build/glib2.0-7ZsPUq/glib2.0-2.48.2/./gio/gsocket.c:3543
#5  0x00007fd776dbe04a in g_main_context_dispatch (context=0x7fd720153100)
    at /build/glib2.0-7ZsPUq/glib2.0-2.48.2/./glib/gmain.c:3154
#6  0x00007fd776dbe04a in g_main_context_dispatch (context=context@entry=0x7fd720153100)
    at /build/glib2.0-7ZsPUq/glib2.0-2.48.2/./glib/gmain.c:3769
#7  0x00007fd776dbe3f0 in g_main_context_iterate (context=0x7fd720153100, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /build/glib2.0-7ZsPUq/glib2.0-2.48.2/./glib/gmain.c:3840
#8  0x00007fd776dbe712 in g_main_loop_run (loop=0x7fd720152f70) at /build/glib2.0-7ZsPUq/glib2.0-2.48.2/./glib/gmain.c:4034
#9  0x00007fd756cc7f14 in  () at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstnice15.so
#10 0x00007fd7736c3f46 in gst_base_src_get_range (src=src@entry=0x7fd75c05dbd0 [GstNiceSrc], offset=offset@entry=18446744073709551615, length=4096, buf=buf@entry=0x7fd718ff0c78) at gstbasesrc.c:2460
#11 0x00007fd7736c5b25 in gst_base_src_loop (pad=0x7fd75c054710 [GstPad]) at gstbasesrc.c:2736
#12 0x00007fd777378c5b in gst_task_func (task=0x7fd72c04f5f0 [GstTask]) at gsttask.c:344
#13 0x00007fd776de55ee in g_thread_pool_thread_proxy (data=<optimized out>)
    at /build/glib2.0-7ZsPUq/glib2.0-2.48.2/./glib/gthreadpool.c:307
#14 0x00007fd776de4c55 in g_thread_proxy (data=0x7fd73408e370) at /build/glib2.0-7ZsPUq/glib2.0-2.48.2/./glib/gthread.c:780
#15 0x00007fd777ebb6ba in start_thread (arg=0x7fd718ff1700) at pthread_create.c:333
#16 0x00007fd77587b41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) c
Continuing.
^C
Program received signal SIGINT, Interrupt.
0x00007fd77586f74d in poll () at ../sysdeps/unix/syscall-template.S:84
84      ../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) bt
#0  0x00007fd77586f74d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fd776dbe38c in g_main_context_iterate (priority=2147483647, n_fds=5, fds=0x7fd72c011fd0, timeout=<optimized out>, context=0x7fd720153100) at /build/glib2.0-7ZsPUq/glib2.0-2.48.2/./glib/gmain.c:4135
#2  0x00007fd776dbe38c in g_main_context_iterate (context=0x7fd720153100, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /build/glib2.0-7ZsPUq/glib2.0-2.48.2/./glib/gmain.c:3835
#3  0x00007fd776dbe712 in g_main_loop_run (loop=0x7fd720152f70) at /build/glib2.0-7ZsPUq/glib2.0-2.48.2/./glib/gmain.c:4034
#4  0x00007fd756cc7f14 in  () at /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstnice15.so
#5  0x00007fd7736c3f46 in gst_base_src_get_range (src=src@entry=0x7fd75c05dbd0 [GstNiceSrc], offset=offset@entry=18446744073709551615, length=4096, buf=buf@entry=0x7fd718ff0c78) at gstbasesrc.c:2460
#6  0x00007fd7736c5b25 in gst_base_src_loop (pad=0x7fd75c054710 [GstPad]) at gstbasesrc.c:2736
#7  0x00007fd777378c5b in gst_task_func (task=0x7fd72c04f5f0 [GstTask]) at gsttask.c:344
#8  0x00007fd776de55ee in g_thread_pool_thread_proxy (data=<optimized out>)
    at /build/glib2.0-7ZsPUq/glib2.0-2.48.2/./glib/gthreadpool.c:307
#9  0x00007fd776de4c55 in g_thread_proxy (data=0x7fd73408e370) at /build/glib2.0-7ZsPUq/glib2.0-2.48.2/./glib/gthread.c:780
#10 0x00007fd777ebb6ba in start_thread (arg=0x7fd718ff1700) at pthread_create.c:333
#11 0x00007fd77587b41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) info line *0x00007fd773dd4a10
Line 2705 of "/build/glib2.0-7ZsPUq/glib2.0-2.48.2/./gio/gsocket.c"
   starts at address 0x7fd773dd49f8 <g_socket_get_available_bytes+104>
   and ends at 0x7fd773dd4a20 <g_socket_get_available_bytes+144>.
(gdb) disas 0x00007fd773dd4a10
Dump of assembler code for function g_socket_get_available_bytes:
   0x00007fd773dd4990 <+0>:     push   %rbx
   0x00007fd773dd4991 <+1>:     mov    %rdi,%rbx
   0x00007fd773dd4994 <+4>:     sub    $0x10,%rsp
   0x00007fd773dd4998 <+8>:     mov    %fs:0x28,%rax
   0x00007fd773dd49a1 <+17>:    mov    %rax,0x8(%rsp)
   0x00007fd773dd49a6 <+22>:    xor    %eax,%eax
   0x00007fd773dd49a8 <+24>:    callq  0x7fd773dd3a20 <g_socket_get_type>
   0x00007fd773dd49ad <+29>:    test   %rbx,%rbx
   0x00007fd773dd49b0 <+32>:    je     0x7fd773dd49ce <g_socket_get_available_bytes+62>
   0x00007fd773dd49b2 <+34>:    mov    (%rbx),%rdx
   0x00007fd773dd49b5 <+37>:    test   %rdx,%rdx
   0x00007fd773dd49b8 <+40>:    je     0x7fd773dd49bf <g_socket_get_available_bytes+47>
   0x00007fd773dd49ba <+42>:    cmp    (%rdx),%rax
   0x00007fd773dd49bd <+45>:    je     0x7fd773dd49f8 <g_socket_get_available_bytes+104>
   0x00007fd773dd49bf <+47>:    mov    %rax,%rsi
   0x00007fd773dd49c2 <+50>:    mov    %rbx,%rdi
   0x00007fd773dd49c5 <+53>:    callq  0x7fd773d90bc0 <g_type_check_instance_is_a@plt>
   0x00007fd773dd49ca <+58>:    test   %eax,%eax
   0x00007fd773dd49cc <+60>:    jne    0x7fd773dd49f8 <g_socket_get_available_bytes+104>
   0x00007fd773dd49ce <+62>:    lea    0x9e18c(%rip),%rdx        # 0x7fd773e72b61
   0x00007fd773dd49d5 <+69>:    lea    0x9ecc4(%rip),%rsi        # 0x7fd773e736a0 <__func__.19121>
   0x00007fd773dd49dc <+76>:    lea    0x90515(%rip),%rdi        # 0x7fd773e64ef8
   0x00007fd773dd49e3 <+83>:    callq  0x7fd773d8f4c0 <g_return_if_fail_warning@plt>
   0x00007fd773dd49e8 <+88>:    mov    $0xffffffffffffffff,%rdx
   0x00007fd773dd49ef <+95>:    jmp    0x7fd773dd4a20 <g_socket_get_available_bytes+144>
   0x00007fd773dd49f1 <+97>:    nopl   0x0(%rax)
   0x00007fd773dd49f8 <+104>:   mov    0x18(%rbx),%rax
   0x00007fd773dd49fc <+108>:   lea    0x4(%rsp),%rdx
   0x00007fd773dd4a01 <+113>:   mov    $0x541b,%esi
   0x00007fd773dd4a06 <+118>:   mov    0xc(%rax),%edi
   0x00007fd773dd4a09 <+121>:   xor    %eax,%eax
   0x00007fd773dd4a0b <+123>:   callq  0x7fd773d8f610 <ioctl@plt>
   0x00007fd773dd4a10 <+128>:   test   %eax,%eax
   0x00007fd773dd4a12 <+130>:   mov    $0xffffffffffffffff,%rdx
   0x00007fd773dd4a19 <+137>:   js     0x7fd773dd4a20 <g_socket_get_available_bytes+144>
   0x00007fd773dd4a1b <+139>:   movslq 0x4(%rsp),%rdx
---Type <return> to continue, or q <return> to quit---/0x00007fd773dd4a10
   0x00007fd773dd4a20 <+144>:   mov    0x8(%rsp),%rcx
   0x00007fd773dd4a25 <+149>:   xor    %fs:0x28,%rcx
   0x00007fd773dd4a2e <+158>:   mov    %rdx,%rax
   0x00007fd773dd4a31 <+161>:   jne    0x7fd773dd4a39 <g_socket_get_available_bytes+169>
   0x00007fd773dd4a33 <+163>:   add    $0x10,%rsp
   0x00007fd773dd4a37 <+167>:   pop    %rbx
   0x00007fd773dd4a38 <+168>:   retq
   0x00007fd773dd4a39 <+169>:   callq  0x7fd773d8eff0 <__stack_chk_fail@plt>
End of assembler dump.
(gdb)
(gdb)
(gdb)
(gdb) disas 0x7fd773d8f610
Dump of assembler code for function ioctl@plt:
   0x00007fd773d8f610 <+0>:     jmpq   *0x35136a(%rip)        # 0x7fd7740e0980
   0x00007fd773d8f616 <+6>:     pushq  $0x12d
   0x00007fd773d8f61b <+11>:    jmpq   0x7fd773d8e330
End of assembler dump.
(gdb) q

kurento glibnice logs:
2019-04-08T10:53:23,814086 3563 0x00007f7e15bc6700   debug glib                      libnice:0 ()  Agent 0x7f7e0803b000 : added a new pair 0x7f7e08011b90 with foundation '7:2611794125' to stream 1 component 1.
2019-04-08T10:53:23,826123 3563 0x00007f7df3b96700   debug glib                      libnice:0 ()  Agent 0x7f7e0803b000 :STUN transaction retransmitted on pair 0x7f7dd8004e30 (timer=2/7 3/200ms).
2019-04-08T10:53:23,846520 3563 0x00007f7df3b96700   debug glib                      libnice:0 ()  Agent 0x7f7e0803b000 :STUN transaction retransmitted on pair 0x7f7dd8004d80 (timer=2/7 3/200ms).
2019-04-08T10:53:23,867072 3563 0x00007f7df3b96700   debug glib                      libnice:0 ()  Agent 0x7f7e0803b000 :STUN transaction retransmitted on pair 0x7f7dd80048b0 (timer=2/7 3/200ms).
2019-04-08T10:53:23,867168 3563 0x00007f7df3b96700   debug glib                      libnice:0 ()  compact_output_message: **WARNING: SLOW PATH**
2019-04-08T10:53:23,887516 3563 0x00007f7df3b96700   debug glib                      libnice:0 ()  Agent 0x7f7e0803b000 :STUN transaction retransmitted on pair 0x7f7dd8004800 (timer=2/7 3/200ms).
2019-04-08T10:53:23,887609 356

**Comment by j1elo** [comment]
Closing this as it should be reported in upstream libnice (https://gitlab.freedesktop.org/libnice/libnice/)
Also we're going to disable the Issues tab in any repo that is not the bugtracker
